name : Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron : 30 02 * * 1-5 # everyweekday at 8 AM IST
jobs:
  run-postman-tests:
    runs-on: ubuntu-latest #coz ubuntu is opensourece &free

    steps: 
      - name: Checkout the code
        uses: actions/checkout@v6.0.1

      - name: Install nodejs and npm
        uses: actions/setup-node@v6.1.0

      - name: Install Newman and htmlextra golobally
        run: |
             npm install -g newman   
             npm install -g newman-reporter-htmlextra

      - name: Run the postman collection with newman
        run: |
             newman run 'InWarranty-Flow Copy.postman_collection.json' \
             -e QA.postman_environment.json \
             -r cli,htmlextra \
             --reporter-html-export newman-report.html

      - name : Newman Report
        uses:  actions/upload-artifact@v4.6.2
        with: 
         name: Newman Report
         path: newman/*.html
             
   
